### PR TITLE
Fix java9 cannot enter Chinese

### PR DESCRIPTION
**Pull request by wohaopa**
I tried using mixins to make changes. But org.lwjglx cannot use transformer. This is also a desperate move.

### CODE REVIEW

**Comment by wohaopa** [comment]
I use an external queue to store characters. After testing, it is possible to input Chinese. This must be done using a corrected version of InputFix. This is a bug from the lwjglx compatibility layer, which I think is for the best

**Comment by wohaopa** [comment]
Maybe I think it would be nice to fix the compatibility layer

**Comment by eigenraven** [comment]
Have you seen #33 ? It might make InputFix not needed when using lwjgl3ify

**Comment by eigenraven** [comment]
The proper way would be to make textboxes aware of char events, it just requires making a library (probably a class in gtnhlib) that will work on both lwjgl versions, and use glfw char events for text input while using key events for keyboard shortcuts, instead of mixing the two

**Comment by wohaopa** [comment]
> The proper way would be to make textboxes aware of char events, it just requires making a library (probably a class in gtnhlib) that will work on both lwjgl versions, and use glfw char events for text input while using key events for keyboard shortcuts, instead of mixing the two

I have an idea. I found that most GUI text inputs are implemented through `keyTyped()`. By entering the correct characters into `keyTyped()`, text input can be achieved. This is perhaps the simplest method, and it succeeded in Java 8.

Subclasses will override `keyTyped()` to adapt to the correct text box, which I think is unnecessary. So now we just need to provide the characters correctly to `keyTyped()`. In lwjgl3, when inputting Chinese characters, `CharCallback` will not be triggered, only when confirmed will it be continuously triggered. `lwjglx` will store all Chinese characters in `keyEventChars[0]`. In lwjgl2, each input character will trigger a method similar to `KeyCallback`, which is different from lwjgl3. So I suggest using a buffer to cache the input characters instead of `keyEventChars` to provide characters. I think this is appropriate.

In Minecraft, text box input is handled in `keyTyped()`. Entering the correct characters into `keyTyped()` can make the text box work.

We must modify `CharCallback` of `lwjglx` because it is in a forward position. Modifying it will allow characters to enter later.
Perhaps we can complete the above operation by setting a new CharCallback and a new character processing mechanism.

**Comment by wohaopa** [comment]
@eigenraven 
I have two options right now:

1. Rewrite KeyBord to make it behave like lwjgl2 (this will be a destructive change and may introduce unknown bugs).
2. Rewrite charEvent (which includes getCharEvent() in KeyBord and charEvent in Display), which I cannot do without modifying lwjglx.

The root cause of the inability to input Chinese and other multi-character languages is that keys do not correspond one-to-one with characters, and a key may input multiple characters at once. Sometimes, the key does not trigger any keyEvent().

I believe this is a legacy issue with lwjgl2, and lwjgl3 uses two callbacks to solve this problem, perhaps recognizing the issue. However, the compatibility layer of lwjglx has not handled it well, as the behavior of KeyBord in lwjglx is not consistent with that of lwjgl2. The compatibility layer should not be like this.

Alternatively, I could be allowed to use another charEventCallback. This would require modifying the location of the getCharEvent calls within Minecraft to fix.

I cannot fix this bug without modifying charEventCallback, which is where lwjgl3 accepts all input strings, but it now ignores all input Chinese characters.

This is a bug in the lwjglx compatibility layer, and I think KeyBord should behave like lwjgl2, rather than another different API (only in some places).

Therefore, I believe this problem can only be resolved by fixing charEventCallback, and everything else is futile.

All character input in Minecraft comes from charEventCallback, but it ignores Chinese characters.

If KeyBord cannot be modified, please give me a way to modify charEventCallback (calling a class in the configuration file). The callback I reset does not work, possibly because of where I placed it.

**Comment by eigenraven** [comment]
Can you try testing 1.1.43? I implemented handling of multiple char events for a single keypress, and there's also kappa's AWT-based IME handling that you can try turning on in the configs

**Comment by wohaopa** [comment]
> Can you try testing 1.1.43? I implemented handling of multiple char events for a single keypress, and there's also kappa's AWT-based IME handling that you can try turning on in the configs

I am testing, and his fix method is consistent with mine, but it lacks modifications to the Minecraft class. I think an additional mod needs to be added. Now I have found it and it is under construction.

**Comment by wohaopa** [comment]
I have tested https://github.com/GTNewHorizons/lwjgl3ify/pull/33 and discussed it with [[kappa-maintainer](https://github.com/kappa-maintainer)](https://github.com/[kappa-maintainer](https://github.com/kappa-maintainer)). It still has a lot of issues and cannot fix the input at this stage. I have tested this PR with community players and have not found any major issues.

[kappa-maintainer](https://github.com/kappa-maintainer) said that https://github.com/GTNewHorizons/lwjgl3ify/pull/33 is still being tested and cannot be merged.

I have added config options in subsequent submissions.

**Pull request closed without merging**
