### PR TITLE
Add workaround for input method users

### PR DESCRIPTION
**Pull request by kappa-maintainer**
This approach is tricky and need further testing by #chinese-general
This PR also contain a new line breaking algorithm based on icu4j, for which the Mojang version was excluded.

### CODE REVIEW

**Comment by eigenraven** [comment]
Can you run the `spotlessApply` gradle task to reformat the code?

**Comment by kappa-maintainer** [comment]
Connection to spotless is a bit unstable here, so I removed it to speedup gradle

**Comment by kappa-maintainer** [comment]
I got some other idea when I dealing with book signing. I will mark this PR ready to review once it's done

**Comment by kappa-maintainer** [comment]
The wrapper approach is hard to handle NEI and has obvious input delay, so I switched to the current one.
It works by adding an imeOn flag to Display and refuse non-char event when it is true. An IME char Queue is also added to Keyboard to bypass the limited size of keyEventChars[]. The imeOn is switched whenever common IME switching keybind detected or F12 is pressed, the detail of this part may need further test and improvement.

**Review by eigenraven — APPROVED** [review]
I made a few style changes, and disabled the IME hacks by default (you can turn them on and the keybinds in the config now)

**Pull request merged**
