### PR TITLE
Add more default LOTR mod ExtensibleEnums

### PR DESCRIPTION
**Pull request by XJIuPa**
Add LOTR Enums

### CODE REVIEW

**Comment by mist475** [comment]
The formatter wants you to put multiple entries on the same line like this:
`"net.minecraft.event.HoverEvent$Action", "lotr.common.fac.LOTRFaction",
          "lotr.common.quest.LOTRMiniQuestFactory", "lotr.common.world.map.LOTRWaypoint",
          "lotr.common.world.map.LOTRWaypoint$Region", "lotr.common.world.spawning.LOTRInvasions",
          "lotr.common.LOTRShields", "lotr.common.LOTRDimension$DimensionRegion",
          "lotr.common.item.LOTRItemBanner$BannerType", "lotr.common.LOTRAchievement$Category",
`
It would be nice if you add what addon/version of lotr requires this,
Default lotr doesn't need it so I presume some modified version/addon needs it?

**Comment by XJIuPa** [comment]
LOTR v36.14

**Comment by XJIuPa** [comment]
Without these multiple entries, my client would not start at all.

**Comment by mist475** [comment]
I use lotr 36.14 without these and it works fine. What other mods do you use? If you use any lotr addons that's why it's not working, so the name of that addon should be added to the comment for clarity

**Review by eigenraven — APPROVED** [review]

**Pull request merged**
